apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .WebHookName }}
  labels:
    app: {{ .WebHookName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .WebHookName }}
  template:
    metadata:
      labels:
        app: {{ .WebHookName }}
    spec:
      containers:
        - name: {{ .WebHookName }}
          image: harshanarayana/go-webhook:latest
          ports:
            - containerPort: 6543
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /config
              name: exec-options
      volumes:
        - name: exec-options
          configMap:
            name: exec-options
            defaultMode: 0755
            items:
              - key: exec-options.json
                path: exec-options.json
