apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .WebHookName }}
webhooks:
  - name: {{ .WebHookName }}.k8s.io
    clientConfig:
      service:
        name: {{ .WebHookName }}
        namespace: default
        path: "/validating/exec-check"
      caBundle: {{ .CABundle }}
    rules:
      - operations:
          - CONNECT
        apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - "*"
    failurePolicy: Fail
