apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .WebHookName }}
webhooks:
  - name: {{ .WebHookName }}.k8s.io
    clientConfig:
      service:
        name: {{ .WebHookName }}
        namespace: default
        path: "/validating"
      caBundle: {{ .CABundle }}
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - "apps"
        apiVersions:
          - "*"
        resources:
          - "deployments"
    failurePolicy: Fail
